stages:
- build
- deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/singuerinc-works/com.singuerinc.blog:$CI_BUILD_TAG
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/singuerinc-works/com.singuerinc.blog:latest

pages:
  image: ruby:2.3
  stage: build
  environment: production
  script:
  - gem install redcarpet
  - gem install jekyll-paginate
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - tags

pages:push-docker-image:
  variables:
    GIT_STRATEGY: none
  image: docker:git
  services:
  - docker:dind
  environment: production
  stage: deploy
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
  - tags
