# Site settings
title:       "singuerinc"
email:
author:      "Nahuel Scotti"
description: "I make apps in HTML5, Javascript, Node.js, Ruby on Rails among others technologies."
baseurl:     ""
url:         "http://blog.singuerinc.com"
date_format: "%b %-d, %Y"
destination: public

# Google services
google_analytics: 'UA-881783-13'
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: singuerinc-blog

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: singuerinc
bitbucket_username:
stackoverflow_id:
twitter_username: singuerinc
google_plus_id:
linkedin_username:
angellist_username:
medium_id: "@singuerinc"
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: ''
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     12
gems: [jekyll-paginate]
