# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            blog | singuerinc
tagline:          'no rights reserved'
description:      'I’m a full stack developer living in Barcelona. I’m currently working at <a href="http://www.b-reel.com" target="_blank">B-REEL</a>.<br/>I make apps in HTML5, Javascript, Node.js, Ruby on Rails among others technologies.<br/>Feel free to copy anything you need. Carry on!'
url:              http://blog.singuerinc.com

author:
  name:           'Nahuel Scotti'
  url:            https://twitter.com/singuerinc
  github:         https://github.com/singuerinc

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/singuerinc/lanyon

destination: ../public
exclude: [puppet]